name: widget_that_fits
description: "A widget that displays the first child that fits the available space."
version: 0.0.1
homepage: https://github.com/ky1vstar/widget_that_fits

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
